### ISSUE TITLE
Not working!

### ISSUE THREAD

**Issue by MDJHShovon** [DokaDoka/ox_basic#12]
Why are these recipes not working?

![image](https://user-images.githubusercontent.com/66560053/190880028-6ba828ed-6479-4fea-bd44-61b1d21689e2.png)

**Comment by thelindat** [comment]
![image](https://user-images.githubusercontent.com/65407488/190880296-6fdfd7c5-c65b-406c-9ae5-2f819211d126.png)

**Comment by MDJHShovon** [comment]
https://raw.githubusercontent.com/overextended/ox_recipes/esx/recipe.yaml

Used that link! But not working

**Comment by thelindat** [comment]
![image](https://user-images.githubusercontent.com/65407488/190892626-ab7676c6-0f1c-411d-921d-1f30230347d9.png)
yes
