### ISSUE TITLE
Failing to download fivem-appearance

### ISSUE THREAD

**Issue by nwvh** [DokaDoka/ox_basic#28]
There are no releases on Linden's fivem-appearance repo.

![image](https://github.com/overextended/txAdminRecipe/assets/76164598/325ec045-702f-465a-99a3-c04054b64f50)

**Comment by chiwanay** [comment]
change the fivem-appearance line with

  ## illenium-appearance
  - action: download_file
    url: https://github.com/iLLeniumStudios/illenium-appearance/releases/latest/download/illenium-appearance.zip
    path: ./tmp/illenium-appearance.zip
  - action: unzip
    src: ./tmp/illenium-appearance.zip
    dest: ./resources/[ox]

**Comment by thelindat** [comment]
Already been discussed several times on discord. Recipe is dead until I push an update for the ox_core rewrite.
Currently just pending illenium-appearance to merge the ox module and push a release.

No point having people download v0.19 of ox_core when the next update breaks a _lot_ of things.
