### ISSUE TITLE
Template link doesn't work

### ISSUE THREAD

**Issue by Mrwimz** [DokaDoka/ox_basic#29]
**Reproduce:**

Copy the link given , or go in to the recipe.yaml, click raw and copy that link. 
Try to paste it in the select template, see the following results.

Error: Recipe error: invalid yaml
Make sure this is a valid recipe URL.

**Image of error:**

![image](https://github.com/overextended/txAdminRecipe/assets/61792769/4fbc71a6-c5b9-4428-aace-3bf08696bb7b)

**Comment by Ehbw** [comment]
Try using https://raw.githubusercontent.com/overextended/txAdminRecipe/0149d640420d2094aae8e899a029b3402481e346/recipe.yaml as the template URL, I've created a PR to fix the syntax

**Comment by Mrwimz** [comment]
Thanks, fully working now, issue was as you mention because of the two indented lines of code with the query actions
