### ISSUE TITLE
respawn not working

### ISSUE THREAD

**Issue by maxcamorra** [DokaDoka/ox_basic#3]
when I die and try to respawn I get a blackscreen and this error inside the console:

[  script:es_extended] SCRIPT ERROR: 
[  script:es_extended] (nil stack trace)

**Comment by DokaDoka** [comment]
There has got to be more to that error.

Can't repro at all, I need more info.

**Comment by maxcamorra** [comment]
I dont actually know why it happens for me but I used the older ambulancejob version and there works everything fine.
