### ISSUE TITLE
Multiple issues with the recipe resources

### ISSUE THREAD

**Issue by yagizozdamar** [DokaDoka/ox_basic#31]
When you first start the server without doing any modifications, you get the following issues (without order)

> [resources:pe-basiclo] Warning: could not find file `config.json` (defined in fxmanifest.lua:17)
> [resources:ox_core] Warning: could not find file `common/data/*.json` (defined in fxmanifest.lua:16)
> [script:ox_lib] Unable to determine current resource version for 'illenium-appearance'
> [resources:npwd] Warning: could not find client_script `apps/game/client/*.lua` (defined in fxmanifest.lua:6)
> [resources:npwd] Warning: could not find server_script `build-detector.js` (defined in fxmanifest.lua:12)

**Comment by thelindat** [comment]
> [resources:pe-basiclo] Warning: could not find file config.json (defined in fxmanifest.lua:17)
[script:ox_lib] Unable to determine current resource version for 'illenium-appearance'
[resources:npwd] Warning: could not find client_script apps/game/client/*.lua (defined in fxmanifest.lua:6)
[resources:npwd] Warning: could not find server_script build-detector.js (defined in fxmanifest.lua:12)

None of these are related to us nor do they cause any actual issues.
The illenium-appearance one will presumably be resolved when it has a new release.

> [resources:ox_core] Warning: could not find file common/data/*.json (defined in fxmanifest.lua:16)

Pending a new tag on ox_core - just move the `data` directory to the correct path.
